document.addEventListener('DOMContentLoaded', () => {
  'use strict';

  // ── Scroll-triggered fade-in ──────────────────
  // Cards have `opacity: 0; transform: translateY(...)` in CSS so they
  // can fade-in when they scroll into view. The catch: anything already
  // in the viewport at first paint *also* runs that animation, which
  // reads as the page "stretching itself in" on hard reload. Snap those
  // to visible instantly; only animate elements that scroll into view
  // *after* the initial paint.
  const animatedSel = '.feature-card, .why-card, .why-card-small, .usecase-item';
  const animatedEls = document.querySelectorAll(animatedSel);
  if (animatedEls.length > 0) {
    const inViewportNow = (el) => {
      const r = el.getBoundingClientRect();
      return r.bottom > 0 && r.top < (window.innerHeight || document.documentElement.clientHeight);
    };

    const snap = (el) => {
      // Disable transition for one frame so adding .visible doesn't animate.
      const prev = el.style.transition;
      el.style.transition = 'none';
      el.classList.add('visible');
      // Force the browser to commit the no-transition paint, then restore so
      // future state changes (hover etc.) still animate.
      // eslint-disable-next-line no-unused-expressions
      el.offsetHeight;
      requestAnimationFrame(() => { el.style.transition = prev; });
    };

    const observer = new IntersectionObserver((entries) => {
      entries.forEach((entry) => {
        if (!entry.isIntersecting) return;
        const parent = entry.target.parentElement;
        if (parent) {
          const siblings = parent.querySelectorAll(animatedSel);
          const index = Array.prototype.indexOf.call(siblings, entry.target);
          if (index > 0) {
            entry.target.style.transitionDelay = (index * 0.12) + 's';
          }
        }
        entry.target.classList.add('visible');
        observer.unobserve(entry.target);
      });
    }, { threshold: 0.15 });

    animatedEls.forEach((el) => {
      if (inViewportNow(el)) {
        snap(el);
      } else {
        observer.observe(el);
      }
    });
  }

  // ── Mobile nav toggle ─────────────────────────
  const navToggle = document.querySelector('.nav-toggle');
  const navLinks = document.querySelector('.nav-links');
  if (navToggle && navLinks) {
    navToggle.addEventListener('click', () => {
      const isOpen = navLinks.classList.toggle('open');
      navToggle.classList.toggle('open');
      navToggle.setAttribute('aria-expanded', String(isOpen));
    });
    navLinks.querySelectorAll('a').forEach((link) => {
      link.addEventListener('click', () => {
        navLinks.classList.remove('open');
        navToggle.classList.remove('open');
        navToggle.setAttribute('aria-expanded', 'false');
      });
    });
  }

  // ── Nav shadow + active link ──────────────────
  const nav = document.querySelector('.nav');
  const sections = document.querySelectorAll('section[id]');
  const navAnchors = document.querySelectorAll('.nav-links a[href^="#"]');
  function updateNav() {
    if (nav) {
      nav.classList.toggle('nav-scrolled', window.scrollY > 50);
    }
    let currentId = '';
    const scrollY = window.scrollY + 120;
    sections.forEach((section) => {
      const top = section.offsetTop;
      const height = section.offsetHeight;
      if (scrollY >= top && scrollY < top + height) {
        currentId = section.getAttribute('id');
      }
    });
    navAnchors.forEach((a) => {
      a.classList.toggle('active', a.getAttribute('href') === '#' + currentId);
    });
  }
  window.addEventListener('scroll', updateNav, { passive: true });
  updateNav();

  // ── Scroll-to-top ─────────────────────────────
  const scrollTopBtn = document.querySelector('.scroll-top');
  if (scrollTopBtn) {
    window.addEventListener('scroll', () => {
      scrollTopBtn.classList.toggle('visible', window.scrollY > 600);
    }, { passive: true });
    scrollTopBtn.addEventListener('click', () => {
      window.scrollTo({ top: 0, behavior: 'smooth' });
    });
  }

  // ── Terminal typing animation ─────────────────
  // Output generated by: python3 -c 'json.dumps(line)' on actual ./rayforce pipe
  const TERMINAL_FRAMES = [
    { type: 'cmd', text: '$ ./rayforce' },
    { type: 'wait', ms: 300 },
    { type: 'cmd', text: '\u2023 (set t (table [Symbol Side Qty]', prompt: true },
    { type: 'cmd', text: '    (list [AAPL GOOG MSFT AAPL GOOG]' },
    { type: 'cmd', text: '          [Buy Sell Buy Sell Buy]' },
    { type: 'cmd', text: '          [100 200 150 300 250])))' },
    { type: 'wait', ms: 400 },
    { type: 'out', lines: [
      '<span class="t-dim">\u250c\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u252c\u2500\u2500\u2500\u2500\u2500\u2500\u252c\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2510</span>',
      '<span class="t-dim">\u2502</span> <span class="t-key">Symbol</span> <span class="t-dim">\u2502</span> <span class="t-key">Side</span> <span class="t-dim">\u2502</span>         <span class="t-key">Qty</span>         <span class="t-dim">\u2502</span>',
      '<span class="t-dim">\u2502  sym   \u2502 sym  \u2502         i64         \u2502</span>',
      '<span class="t-dim">\u251c\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u253c\u2500\u2500\u2500\u2500\u2500\u2500\u253c\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2524</span>',
      '<span class="t-dim">\u2502</span> <span class="t-str">AAPL</span>   <span class="t-dim">\u2502</span> Buy  <span class="t-dim">\u2502</span> <span class="t-num">100</span>                 <span class="t-dim">\u2502</span>',
      '<span class="t-dim">\u2502</span> <span class="t-str">GOOG</span>   <span class="t-dim">\u2502</span> Sell <span class="t-dim">\u2502</span> <span class="t-num">200</span>                 <span class="t-dim">\u2502</span>',
      '<span class="t-dim">\u2502</span> <span class="t-str">MSFT</span>   <span class="t-dim">\u2502</span> Buy  <span class="t-dim">\u2502</span> <span class="t-num">150</span>                 <span class="t-dim">\u2502</span>',
      '<span class="t-dim">\u2502</span> <span class="t-str">AAPL</span>   <span class="t-dim">\u2502</span> Sell <span class="t-dim">\u2502</span> <span class="t-num">300</span>                 <span class="t-dim">\u2502</span>',
      '<span class="t-dim">\u2502</span> <span class="t-str">GOOG</span>   <span class="t-dim">\u2502</span> Buy  <span class="t-dim">\u2502</span> <span class="t-num">250</span>                 <span class="t-dim">\u2502</span>',
      '<span class="t-dim">\u251c\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2534\u2500\u2500\u2500\u2500\u2500\u2500\u2534\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2524</span>',
      '<span class="t-dim">\u2502 5 rows (5 shown) 3 columns (3 shown)\u2502</span>',
      '<span class="t-dim">\u2514\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2518</span>',
      '',
    ]},
    { type: 'wait', ms: 1200 },
    { type: 'cmd', text: '\u2023 (select {from:t by: Symbol Qty: (sum Qty)})', prompt: true },
    { type: 'wait', ms: 400 },
    { type: 'out', lines: [
      '<span class="t-dim">\u250c\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u252c\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2510</span>',
      '<span class="t-dim">\u2502</span> <span class="t-key">Symbol</span> <span class="t-dim">\u2502</span>            <span class="t-key">Qty</span>             <span class="t-dim">\u2502</span>',
      '<span class="t-dim">\u2502  sym   \u2502            i64             \u2502</span>',
      '<span class="t-dim">\u251c\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u253c\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2524</span>',
      '<span class="t-dim">\u2502</span> <span class="t-str">AAPL</span>   <span class="t-dim">\u2502</span> <span class="t-num">400</span>                        <span class="t-dim">\u2502</span>',
      '<span class="t-dim">\u2502</span> <span class="t-str">GOOG</span>   <span class="t-dim">\u2502</span> <span class="t-num">450</span>                        <span class="t-dim">\u2502</span>',
      '<span class="t-dim">\u2502</span> <span class="t-str">MSFT</span>   <span class="t-dim">\u2502</span> <span class="t-num">150</span>                        <span class="t-dim">\u2502</span>',
      '<span class="t-dim">\u251c\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2534\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2524</span>',
      '<span class="t-dim">\u2502 3 rows (3 shown) 2 columns (2 shown)\u2502</span>',
      '<span class="t-dim">\u2514\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2518</span>',
      '',
    ]},
    { type: 'wait', ms: 1200 },
    { type: 'cmd', text: "\u2023 (pivot t 'Symbol 'Side 'Qty sum)", prompt: true },
    { type: 'wait', ms: 400 },
    { type: 'out', lines: [
      '<span class="t-dim">\u250c\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u252c\u2500\u2500\u2500\u2500\u2500\u252c\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2510</span>',
      '<span class="t-dim">\u2502</span> <span class="t-key">Symbol</span> <span class="t-dim">\u2502</span> <span class="t-key">Buy</span> <span class="t-dim">\u2502</span>         <span class="t-key">Sell</span>         <span class="t-dim">\u2502</span>',
      '<span class="t-dim">\u2502  sym   \u2502 i64 \u2502         i64          \u2502</span>',
      '<span class="t-dim">\u251c\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u253c\u2500\u2500\u2500\u2500\u2500\u253c\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2524</span>',
      '<span class="t-dim">\u2502</span> <span class="t-str">AAPL</span>   <span class="t-dim">\u2502</span> <span class="t-num">100</span> <span class="t-dim">\u2502</span> <span class="t-num">300</span>                  <span class="t-dim">\u2502</span>',
      '<span class="t-dim">\u2502</span> <span class="t-str">GOOG</span>   <span class="t-dim">\u2502</span> <span class="t-num">250</span> <span class="t-dim">\u2502</span> <span class="t-num">200</span>                  <span class="t-dim">\u2502</span>',
      '<span class="t-dim">\u2502</span> <span class="t-str">MSFT</span>   <span class="t-dim">\u2502</span> <span class="t-num">150</span> <span class="t-dim">\u2502</span> <span class="t-num">0</span>                    <span class="t-dim">\u2502</span>',
      '<span class="t-dim">\u251c\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2534\u2500\u2500\u2500\u2500\u2500\u2534\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2524</span>',
      '<span class="t-dim">\u2502 3 rows (3 shown) 3 columns (3 shown)\u2502</span>',
      '<span class="t-dim">\u2514\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2518</span>',
      '',
    ]},
    { type: 'wait', ms: 4000 },
    { type: 'clear' },
  ];

  class TerminalAnimation {
    constructor(el, frames) {
      this.el = el;
      this.frames = frames;
      this.running = false;
    }

    async start() {
      if (this.running) return;
      this.running = true;
      while (this.running) {
        this.el.innerHTML = '';
        for (const frame of this.frames) {
          if (!this.running) return;
          switch (frame.type) {
            case 'cmd': await this.typeCommand(frame.text, frame.prompt); break;
            case 'out': await this.showOutput(frame.lines); break;
            case 'wait': await this.wait(frame.ms); break;
            case 'clear':
              await this.wait(300);
              this.el.style.opacity = '0';
              await this.wait(300);
              this.el.innerHTML = '';
              this.el.style.opacity = '1';
              break;
          }
        }
      }
    }

    stop() {
      this.running = false;
    }

    async typeCommand(text, prompt) {
      const line = document.createElement('div');
      line.className = 'term-line term-cmd';
      this.el.appendChild(line);

      const cursor = document.createElement('span');
      cursor.className = 'term-cursor';
      cursor.textContent = '\u2588';

      for (let i = 0; i < text.length; i++) {
        if (!this.running) return;
        // Render prompt character (‣) in green
        if (prompt && text[0] === '\u2023') {
          line.innerHTML = '<span class="t-prompt">\u2023</span>' +
            this.escapeHtml(text.slice(1, i + 1));
        } else {
          line.textContent = text.slice(0, i + 1);
        }
        line.appendChild(cursor);
        this.scrollToBottom();
        await this.wait(25 + Math.random() * 35);
      }

      cursor.remove();
      await this.wait(120);
    }

    escapeHtml(s) {
      return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
    }

    async showOutput(lines) {
      for (const html of lines) {
        if (!this.running) return;
        const line = document.createElement('div');
        line.className = 'term-line term-out';
        line.innerHTML = html;
        this.el.appendChild(line);
        this.scrollToBottom();
        await this.wait(35);
      }
    }

    scrollToBottom() {
      this.el.scrollTop = this.el.scrollHeight;
    }

    wait(ms) {
      return new Promise((resolve) => setTimeout(resolve, ms));
    }
  }

  // Start terminal when scrolled into view
  const terminalOutput = document.getElementById('terminal-output');
  if (terminalOutput) {
    const terminal = new TerminalAnimation(terminalOutput, TERMINAL_FRAMES);
    const termObserver = new IntersectionObserver((entries) => {
      entries.forEach((entry) => {
        if (entry.isIntersecting) {
          terminal.start();
          termObserver.unobserve(entry.target);
        }
      });
    }, { threshold: 0.3 });
    termObserver.observe(terminalOutput);
  }
});

/* GitHub widget: fetch live stars/forks via ungh.cc (CDN-cached proxy
 * without GitHub's 60/hour unauthenticated rate limit) with a 1-hour
 * localStorage cache so repeat visits don't refetch. Falls back silently
 * if every source is unreachable. */
(function () {
  const targets = document.querySelectorAll('[data-gh-stat]');
  if (targets.length === 0) return;

  const REPO = 'RayforceDB/rayforce';
  const CACHE_KEY = 'gh-stats:' + REPO;
  const CACHE_TTL = 60 * 60 * 1000; /* 1 hour */

  function fmt(n) {
    if (typeof n !== 'number' || isNaN(n)) return '—';
    if (n >= 10000) return (n / 1000).toFixed(1).replace(/\.0$/, '') + 'k';
    if (n >= 1000)  return (n / 1000).toFixed(1) + 'k';
    return String(n);
  }

  function animateCount(el, target, duration) {
    if (typeof target !== 'number' || isNaN(target)) return;
    const reduce = window.matchMedia && window.matchMedia('(prefers-reduced-motion: reduce)').matches;
    if (reduce) { el.textContent = fmt(target); return; }
    const start = performance.now();
    function tick(now) {
      const t = Math.min(1, (now - start) / duration);
      const eased = 1 - Math.pow(1 - t, 3); /* easeOutCubic */
      el.textContent = fmt(Math.round(target * eased));
      if (t < 1) requestAnimationFrame(tick);
      else el.textContent = fmt(target);
    }
    requestAnimationFrame(tick);
  }

  function paint(stars, forks) {
    targets.forEach(el => {
      const which = el.getAttribute('data-gh-stat');
      const target = which === 'stars' ? stars
                   : which === 'forks' ? forks
                   : NaN;
      animateCount(el, target, 900);
    });
  }

  function readCache() {
    try {
      const raw = localStorage.getItem(CACHE_KEY);
      if (!raw) return null;
      const v = JSON.parse(raw);
      if (!v || (Date.now() - v.t) > CACHE_TTL) return null;
      return v;
    } catch (e) { return null; }
  }

  function writeCache(stars, forks) {
    try { localStorage.setItem(CACHE_KEY, JSON.stringify({ t: Date.now(), stars, forks })); } catch (e) {}
  }

  /* If we have a fresh cached value, paint it instantly without a network roundtrip. */
  const cached = readCache();
  if (cached) { paint(cached.stars, cached.forks); return; }

  /* Primary: ungh.cc (CDN-cached, no rate limit). Response shape: { repo: { stars, forks, ... } } */
  fetch('https://ungh.cc/repos/' + REPO)
    .then(r => r.ok ? r.json() : Promise.reject(new Error('ungh ' + r.status)))
    .then(d => {
      const stars = d && d.repo && d.repo.stars;
      const forks = d && d.repo && d.repo.forks;
      if (typeof stars !== 'number' || typeof forks !== 'number') throw new Error('ungh shape');
      writeCache(stars, forks);
      paint(stars, forks);
    })
    .catch(() => {
      /* Fallback: direct GitHub API. Often 403s on busy IPs but free when it works. */
      return fetch('https://api.github.com/repos/' + REPO, { headers: { Accept: 'application/vnd.github+json' } })
        .then(r => r.ok ? r.json() : Promise.reject(new Error('gh ' + r.status)))
        .then(d => {
          writeCache(d.stargazers_count, d.forks_count);
          paint(d.stargazers_count, d.forks_count);
        });
    })
    .catch(() => {
      /* Leave the static "—" placeholders. Users still get a working link. */
    });
})();
