name: Build and Release

on:
  push:
    tags:
      - 'v*.*'
      - 'nightly'

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: x86_64
          - os: macos-14
            arch: arm64
          - os: windows-latest
            arch: x86_64
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4

    - name: Upload RELEASE.md
      if: matrix.os == 'ubuntu-latest'
      uses: actions/upload-artifact@v4
      with:
        name: release-notes
        path: RELEASE.md

    - name: Install dependencies (Linux)
      if: runner.os == 'Linux'
      run: sudo apt-get install -y build-essential

    - name: Make (Linux)
      if: runner.os == 'Linux'
      run: make CC="gcc" RELEASE_CFLAGS="-fPIC -Wall -Wextra -std=c17 -Ofast -march=x86-64 -msse -msse2 -mavx -mavx2 -fassociative-math -ftree-vectorize  -mfma -mpclmul -mbmi2 -m64" release

    - name: Setup MSYS2 (Windows)
      if: runner.os == 'Windows'
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: mingw-w64-x86_64-clang mingw-w64-x86_64-lld make

    - name: Make (Windows)
      if: runner.os == 'Windows'
      shell: msys2 {0}
      run: |
        export TEMP=/tmp TMP=/tmp
        make release

    - name: Install dependencies (macOS)
      if: runner.os == 'macOS'
      run: |
        if ! command -v clang &> /dev/null
        then
          xcode-select --install
        fi

    - name: Make (macOS)
      if: runner.os == 'macOS'
      run: make RELEASE_CFLAGS="-fPIC -Wall -Wextra -std=c17 -O3 -fsigned-char -march=native -fassociative-math -ftree-vectorize -funsafe-math-optimizations -funroll-loops -m64 -flax-vector-conversions -fno-math-errno" release
 
    - name: Create build directory and copy binary (Linux)
      if: runner.os == 'Linux'
      run: |
        mkdir build
        cp ./rayforce ./build/
        cp -r ./examples ./build/
        cp ./LICENSE-BIN.md ./build/LICENSE.md
        cd ./build
        tar -cvpzf ../${{ matrix.os }}-${{ matrix.arch }}.tar.gz *

    - name: Create build directory and copy binary (Windows)
      if: runner.os == 'Windows'
      shell: msys2 {0}
      run: |
        mkdir build
        cp ./rayforce.exe ./build/
        cp -r ./examples ./build/
        cp ./LICENSE-BIN.md ./build/LICENSE.md
        cd build
        7z a ../${{ matrix.os }}-${{ matrix.arch }}.zip .

    - name: Create build directory and copy binary (macOS)
      if: runner.os == 'macOS'
      run: |
        mkdir build
        cp ./rayforce ./build/
        cp -r ./examples ./build/
        cp ./LICENSE-BIN.md ./build/LICENSE.md
        cd ./build
        tar -cvpzf ../${{ matrix.os }}-${{ matrix.arch }}.tar.gz *

    - name: Upload Artifact (Linux)
      uses: actions/upload-artifact@v4
      if: runner.os == 'Linux'
      with:
        name: ${{ matrix.os }}-${{ matrix.arch }}.tar.gz
        path: ${{ matrix.os }}-${{ matrix.arch }}.tar.gz

    - name: Upload Artifact (Windows)
      uses: actions/upload-artifact@v4
      if: runner.os == 'Windows'
      with:
        name: ${{ matrix.os }}-${{ matrix.arch }}.zip
        path: ${{ matrix.os }}-${{ matrix.arch }}.zip

    - name: Upload Artifact (macOS)
      uses: actions/upload-artifact@v4
      if: runner.os == 'macOS'
      with:
        name: ${{ matrix.os }}-${{ matrix.arch }}.tar.gz
        path: ${{ matrix.os }}-${{ matrix.arch }}.tar.gz

  create-release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4

      - name: Set tag name
        id: set_tag
        run: echo "TAG_NAME=$(echo ${{ github.ref }} | sed 's@refs/tags/@@')" >> $GITHUB_ENV

      - name: Create Release and Upload Assets
        run: |
          gh release create ${{ env.TAG_NAME }} \
            --repo ${{ github.repository }} \
            --title ${{ env.TAG_NAME }} \
            --notes-file ${{ github.workspace }}/release-notes/RELEASE.md \
            --draft=false \
            --prerelease=false \
            ${{ github.workspace }}/ubuntu-latest-x86_64.tar.gz/ubuntu-latest-x86_64.tar.gz \
            ${{ github.workspace }}/macos-14-arm64.tar.gz/macos-14-arm64.tar.gz \
            ${{ github.workspace }}/windows-latest-x86_64.zip/windows-latest-x86_64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
